apiVersion: v1
kind: ConfigMap
metadata:
  name: memories-config
data:
  PORT: "3002"
  UPLOAD_DIR: "/usr/src/app/uploads/"
  AWS_S3_BUCKET: "memorybook-media"
  NODE_ENV: "production"
  AWS_REGION: "ap-south-1"
