apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
      - name: auth
        image: 929140636859.dkr.ecr.ap-south-1.amazonaws.com/scrapbook-auth:latest
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: auth-config
        - secretRef:
            name: scrapbook-secrets
        volumeMounts:
        - name: storage
          mountPath: /data/storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage-pvc
