apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social
  template:
    metadata:
      labels:
        app: social
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
      - name: social
        image: 929140636859.dkr.ecr.ap-south-1.amazonaws.com/scrapbook-social:latest
        ports:
        - containerPort: 3003
        envFrom:
        - configMapRef:
            name: social-config
        - secretRef:
            name: scrapbook-secrets
        volumeMounts:
        - name: social-data
          mountPath: /usr/src/app/data
        - name: uploads-data
          mountPath: /usr/src/app/uploads
      volumes:
      - name: social-data
        persistentVolumeClaim:
          claimName: social-pvc
      - name: uploads-data
        persistentVolumeClaim:
          claimName: uploads-pvc
